title:       "Язык C"
description: "Базовые типы. Представление значений вещественных базовых типов в памяти.Диапазоны значений вещественных базовых типов."
copyright:   "© Группа 22210"

header_pages:
  - index.md
