title:       "Язык C"
description: "Понятие функции. Описание функций в Си. Передаваемые параметры. Передача параметров через стек вызовов. Возвращаемые значения."
copyright:   "© Группа 22210"

header_pages:
  - index.md
