title:       "Структуры данных"
description: "Дерево, как частный вид графа. Способы представления деревьев в ЭВМ: левая и правая скобочная запись, список предков, указате"
copyright:   "© Группа 22210"

header_pages:
  - index.md
